version: '3'
services:
  postgres: 
    image: ${DB_DRIVER}
    volumes:
      - ./volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'

